version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/local/apache2/htdocs
      - ./certs:/usr/local/apache2/conf
    restart: always
